/**
 * PMCF Report Template Configuration
 *
 * Post-Market Clinical Follow-up Evaluation Report
 * MDR 2017/745 compliant
 */

import type { DocxTemplateConfig } from './validation-report.template.js';

export const pmcfReportTemplate: DocxTemplateConfig = {
  id: 'pmcf-report',
  name: 'Post-Market Clinical Follow-up (PMCF) Evaluation Report',
  version: '1.0',
  regulatoryStandard: 'MDR 2017/745 Article 61, Annex XIV Part B',

  styles: {
    bodyFont: 'Times New Roman',
    bodyFontSize: 12,
    headingFont: 'Arial',
    margins: {
      top: 2.5,
      bottom: 2.5,
      left: 2.5,
      right: 2.5,
      unit: 'cm',
    },
    pageNumbering: true,
    watermark: 'CONFIDENTIAL',
  },

  headerFooter: {
    header: {
      left: 'PMCF Evaluation Report',
      right: '{version} | {date}',
    },
    footer: {
      left: 'MDR 2017/745 Article 61',
      center: 'Page {page} of {pages}',
      right: '{device_name}',
    },
    firstPageDifferent: true,
  },

  sections: [
    {
      id: 'cover-page',
      title: 'Cover Page',
      level: 1,
      required: true,
      contentType: 'mixed',
      placeholder: 'Document title, device name, reporting period, version, date, author',
    },
    {
      id: 'toc',
      title: 'Table of Contents',
      level: 1,
      required: true,
      contentType: 'list',
      placeholder: 'Auto-generated table of contents',
    },
    {
      id: 'executive-summary',
      title: '1. Executive Summary',
      level: 1,
      required: true,
      contentType: 'text',
      placeholder: 'High-level summary of PMCF findings for reporting period',
    },
    {
      id: 'device-identification',
      title: '2. Device Identification',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'device-name',
          title: '2.1 Device Name and UDI',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Product name, UDI-DI, model numbers',
        },
        {
          id: 'device-classification',
          title: '2.2 Device Classification',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Risk class, intended use, indications',
        },
        {
          id: 'reporting-period',
          title: '2.3 Reporting Period',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Start date to end date of PMCF data collection',
        },
      ],
    },
    {
      id: 'pmcf-objectives',
      title: '3. PMCF Study Objectives',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'pmcf-objectives-primary',
          title: '3.1 Primary Objectives',
          level: 2,
          required: true,
          contentType: 'list',
          placeholder: 'Primary PMCF objectives from PMCF plan',
        },
        {
          id: 'pmcf-objectives-secondary',
          title: '3.2 Secondary Objectives',
          level: 2,
          required: false,
          contentType: 'list',
          placeholder: 'Secondary and exploratory objectives',
        },
        {
          id: 'pmcf-objectives-endpoints',
          title: '3.3 Clinical Performance Endpoints',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Table of endpoints tracked during PMCF',
        },
      ],
    },
    {
      id: 'pmcf-methods',
      title: '4. PMCF Methods',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'pmcf-methods-design',
          title: '4.1 Study Design',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'PMCF methodology (registry, survey, prospective study, etc.)',
        },
        {
          id: 'pmcf-methods-data-sources',
          title: '4.2 Data Sources',
          level: 2,
          required: true,
          contentType: 'list',
          placeholder: 'Clinical registries, vigilance data, complaint data, literature',
        },
        {
          id: 'pmcf-methods-population',
          title: '4.3 Target Population',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Patient population, sample size, inclusion criteria',
        },
      ],
    },
    {
      id: 'pmcf-results',
      title: '5. PMCF Results',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'pmcf-results-overview',
          title: '5.1 Results Overview',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Summary of data collected during reporting period',
        },
        {
          id: 'pmcf-results-performance',
          title: '5.2 Clinical Performance Results',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Dynamic table: Endpoint, N, Result, 95% CI, Comparison to Pre-market',
        },
        {
          id: 'pmcf-results-safety',
          title: '5.3 Safety Data',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Adverse events, incidents, complaints summary',
        },
        {
          id: 'pmcf-results-use-errors',
          title: '5.4 Use Errors and User Feedback',
          level: 2,
          required: false,
          contentType: 'text',
          placeholder: 'User errors, usability issues, training feedback',
        },
      ],
    },
    {
      id: 'vigilance-data',
      title: '6. Vigilance and Complaint Data',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'vigilance-incidents',
          title: '6.1 Incidents and Field Safety Notices',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Summary table of incidents, FSCAs, FSNs during period',
        },
        {
          id: 'vigilance-complaints',
          title: '6.2 Complaint Trends',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Analysis of complaint patterns and frequency',
        },
        {
          id: 'vigilance-trend-analysis',
          title: '6.3 Trend Analysis',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Statistical trend analysis of adverse events',
        },
      ],
    },
    {
      id: 'literature-review',
      title: '7. Literature Review Update',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'literature-search',
          title: '7.1 Literature Search',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Update on literature search for reporting period',
        },
        {
          id: 'literature-findings',
          title: '7.2 Key Findings',
          level: 2,
          required: false,
          contentType: 'text',
          placeholder: 'Relevant publications and their impact on device evaluation',
        },
      ],
    },
    {
      id: 'benefit-risk-update',
      title: '8. Benefit-Risk Re-evaluation',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'benefit-risk-changes',
          title: '8.1 Changes to Benefit-Risk Profile',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Assessment of any changes in benefit-risk based on PMCF data',
        },
        {
          id: 'benefit-risk-acceptability',
          title: '8.2 Benefit-Risk Acceptability',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Confirmation of continued acceptability or concerns identified',
        },
      ],
    },
    {
      id: 'corrective-actions',
      title: '9. Corrective and Preventive Actions',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'corrective-actions-taken',
          title: '9.1 Actions Taken',
          level: 2,
          required: false,
          contentType: 'table',
          placeholder: 'Table of CAPAs implemented during reporting period',
        },
        {
          id: 'corrective-actions-planned',
          title: '9.2 Planned Actions',
          level: 2,
          required: false,
          contentType: 'list',
          placeholder: 'Future actions identified from PMCF analysis',
        },
      ],
    },
    {
      id: 'conclusions',
      title: '10. Conclusions',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'conclusions-findings',
          title: '10.1 Summary of Findings',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Key findings from PMCF evaluation',
        },
        {
          id: 'conclusions-compliance',
          title: '10.2 Continued Compliance',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Statement of continued compliance with MDR requirements',
        },
        {
          id: 'conclusions-recommendations',
          title: '10.3 Recommendations',
          level: 2,
          required: true,
          contentType: 'list',
          placeholder: 'Recommendations for CER update, labeling changes, PMCF plan modifications',
        },
      ],
    },
    {
      id: 'references',
      title: '11. References',
      level: 1,
      required: true,
      contentType: 'list',
      placeholder: 'Numbered list of all cited references',
    },
    {
      id: 'appendix-raw-data',
      title: 'Appendix A: Raw Data Summary',
      level: 1,
      required: false,
      contentType: 'table',
      placeholder: 'Detailed data tables and statistical analyses',
    },
  ],
};
