/**
 * PSUR Report Template Configuration
 *
 * Periodic Safety Update Report
 * MDR 2017/745 Article 86 compliant
 */

import type { DocxTemplateConfig } from './validation-report.template.js';

export const psurReportTemplate: DocxTemplateConfig = {
  id: 'psur-report',
  name: 'Periodic Safety Update Report (PSUR)',
  version: '1.0',
  regulatoryStandard: 'MDR 2017/745 Article 86',

  styles: {
    bodyFont: 'Times New Roman',
    bodyFontSize: 12,
    headingFont: 'Arial',
    margins: {
      top: 2.5,
      bottom: 2.5,
      left: 2.5,
      right: 2.5,
      unit: 'cm',
    },
    pageNumbering: true,
    watermark: 'CONFIDENTIAL',
  },

  headerFooter: {
    header: {
      left: 'Periodic Safety Update Report',
      right: '{version} | {date}',
    },
    footer: {
      left: 'MDR 2017/745 Article 86',
      center: 'Page {page} of {pages}',
      right: '{device_name}',
    },
    firstPageDifferent: true,
  },

  sections: [
    {
      id: 'cover-page',
      title: 'Cover Page',
      level: 1,
      required: true,
      contentType: 'mixed',
      placeholder: 'Document title, device name, reporting period, version, date, author',
    },
    {
      id: 'toc',
      title: 'Table of Contents',
      level: 1,
      required: true,
      contentType: 'list',
      placeholder: 'Auto-generated table of contents',
    },
    {
      id: 'executive-summary',
      title: '1. Executive Summary',
      level: 1,
      required: true,
      contentType: 'text',
      placeholder: 'High-level summary of safety findings and actions for reporting period',
    },
    {
      id: 'device-identification',
      title: '2. Device and Manufacturer Information',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'device-details',
          title: '2.1 Device Details',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Product name, UDI-DI, model numbers, classification',
        },
        {
          id: 'manufacturer-details',
          title: '2.2 Manufacturer Details',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Manufacturer name, address, SRN',
        },
        {
          id: 'reporting-period',
          title: '2.3 Reporting Period',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Start date to end date of PSUR period',
        },
        {
          id: 'regulatory-status',
          title: '2.4 Regulatory Status',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'CE mark date, notified body, certificate numbers',
        },
      ],
    },
    {
      id: 'sales-distribution',
      title: '3. Sales and Distribution Data',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'sales-volume',
          title: '3.1 Sales Volume',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Table of units sold by region during reporting period',
        },
        {
          id: 'cumulative-exposure',
          title: '3.2 Cumulative Patient Exposure',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Estimated cumulative patient exposure to date',
        },
      ],
    },
    {
      id: 'vigilance-analysis',
      title: '4. Vigilance Data Analysis',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'vigilance-summary',
          title: '4.1 Summary of Incidents',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Table: Incident type, Count, Severity, FSCA issued (Y/N)',
        },
        {
          id: 'vigilance-serious',
          title: '4.2 Serious Incidents',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Detailed analysis of serious incidents and outcomes',
        },
        {
          id: 'vigilance-trend',
          title: '4.3 Trend Analysis',
          level: 2,
          required: true,
          contentType: 'mixed',
          placeholder: 'Statistical trend analysis: increasing, stable, decreasing',
        },
        {
          id: 'vigilance-root-cause',
          title: '4.4 Root Cause Analysis',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Root causes identified from incident investigations',
        },
      ],
    },
    {
      id: 'fsca-summary',
      title: '5. Field Safety Corrective Actions (FSCAs)',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'fsca-list',
          title: '5.1 FSCAs Issued During Period',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Table: FSCA ID, Date, Type, Reason, Status',
        },
        {
          id: 'fsca-effectiveness',
          title: '5.2 Effectiveness of FSCAs',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Assessment of FSCA implementation and effectiveness',
        },
      ],
    },
    {
      id: 'complaint-analysis',
      title: '6. Complaint Data Analysis',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'complaint-summary',
          title: '6.1 Complaint Summary',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Table: Complaint category, Count, Rate per 1000 units',
        },
        {
          id: 'complaint-trends',
          title: '6.2 Complaint Trends',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Analysis of complaint patterns and emerging issues',
        },
        {
          id: 'complaint-actions',
          title: '6.3 Actions Taken',
          level: 2,
          required: false,
          contentType: 'text',
          placeholder: 'Corrective actions implemented in response to complaints',
        },
      ],
    },
    {
      id: 'pmcf-updates',
      title: '7. PMCF Data Updates',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'pmcf-ongoing',
          title: '7.1 Ongoing PMCF Activities',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Status of PMCF studies and data collection',
        },
        {
          id: 'pmcf-findings',
          title: '7.2 Relevant PMCF Findings',
          level: 2,
          required: false,
          contentType: 'text',
          placeholder: 'PMCF findings relevant to safety evaluation',
        },
      ],
    },
    {
      id: 'literature-review',
      title: '8. Literature and Market Surveillance',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'literature-search',
          title: '8.1 Literature Search Results',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Update on literature surveillance for reporting period',
        },
        {
          id: 'similar-devices',
          title: '8.2 Similar Devices and Technologies',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Safety issues reported for similar devices',
        },
      ],
    },
    {
      id: 'benefit-risk-assessment',
      title: '9. Benefit-Risk Re-evaluation',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'benefit-risk-current',
          title: '9.1 Current Benefit-Risk Profile',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Updated benefit-risk assessment based on PSUR period data',
        },
        {
          id: 'benefit-risk-changes',
          title: '9.2 Changes to Risk Assessment',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'New risks identified or changes to risk levels',
        },
        {
          id: 'benefit-risk-acceptability',
          title: '9.3 Benefit-Risk Acceptability',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Confirmation that benefits continue to outweigh risks',
        },
      ],
    },
    {
      id: 'corrective-actions',
      title: '10. Corrective and Preventive Actions',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'corrective-actions-implemented',
          title: '10.1 Actions Implemented',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Table: Action ID, Date, Description, Status, Effectiveness',
        },
        {
          id: 'corrective-actions-planned',
          title: '10.2 Planned Actions',
          level: 2,
          required: true,
          contentType: 'list',
          placeholder: 'Future corrective actions identified from PSUR analysis',
        },
      ],
    },
    {
      id: 'conclusions',
      title: '11. Conclusions and Recommendations',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'conclusions-summary',
          title: '11.1 Summary of Findings',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Key safety findings from PSUR period',
        },
        {
          id: 'conclusions-safety-profile',
          title: '11.2 Safety Profile Assessment',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Overall assessment of device safety profile',
        },
        {
          id: 'conclusions-recommendations',
          title: '11.3 Recommendations',
          level: 2,
          required: true,
          contentType: 'list',
          placeholder: 'Recommendations: CER update, IFU changes, risk management updates',
        },
        {
          id: 'conclusions-regulatory',
          title: '11.4 Regulatory Compliance',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Statement of continued regulatory compliance',
        },
      ],
    },
    {
      id: 'appendix-incidents',
      title: 'Appendix A: Detailed Incident List',
      level: 1,
      required: false,
      contentType: 'table',
      placeholder: 'Complete list of all incidents with details',
    },
    {
      id: 'appendix-complaints',
      title: 'Appendix B: Complaint Details',
      level: 1,
      required: false,
      contentType: 'table',
      placeholder: 'Detailed complaint data and categorization',
    },
  ],
};
