/**
 * Validation Report Template Configuration
 *
 * MDR-compliant clinical validation study report template
 * Based on MEDDEV 2.7/1 rev 4 guidelines
 */

export interface TemplateSection {
  id: string;
  title: string;
  level: number; // heading level 1-4
  required: boolean;
  contentType: 'text' | 'table' | 'chart' | 'list' | 'mixed';
  subsections?: TemplateSection[];
  placeholder?: string; // default content hint
}

export interface HeaderFooterConfig {
  header: {
    left?: string;
    center?: string;
    right?: string;
  };
  footer: {
    left?: string;
    center?: string;
    right?: string;
  };
  firstPageDifferent?: boolean;
}

export interface TemplateStyles {
  bodyFont: string;
  bodyFontSize: number;
  headingFont: string;
  margins: {
    top: number;
    bottom: number;
    left: number;
    right: number;
    unit: 'cm' | 'in';
  };
  pageNumbering: boolean;
  watermark?: string;
}

export interface DocxTemplateConfig {
  id: string;
  name: string;
  version: string;
  regulatoryStandard: string;
  sections: TemplateSection[];
  styles: TemplateStyles;
  headerFooter: HeaderFooterConfig;
}

export const validationReportTemplate: DocxTemplateConfig = {
  id: 'validation-report',
  name: 'Clinical Validation Report',
  version: '1.0',
  regulatoryStandard: 'MDR 2017/745 Annex XIV, MEDDEV 2.7/1 rev 4',

  styles: {
    bodyFont: 'Times New Roman',
    bodyFontSize: 12,
    headingFont: 'Arial',
    margins: {
      top: 2.5,
      bottom: 2.5,
      left: 2.5,
      right: 2.5,
      unit: 'cm',
    },
    pageNumbering: true,
    watermark: 'CONFIDENTIAL',
  },

  headerFooter: {
    header: {
      left: 'Clinical Validation Report',
      right: '{version} | {date}',
    },
    footer: {
      left: 'Generated by CORTEX Clinical Affairs Suite',
      center: 'Page {page} of {pages}',
      right: 'Protocol v{protocol_version}',
    },
    firstPageDifferent: true,
  },

  sections: [
    {
      id: 'cover-page',
      title: 'Cover Page',
      level: 1,
      required: true,
      contentType: 'mixed',
      placeholder: 'Document title, version, date, author, approval signatures',
    },
    {
      id: 'toc',
      title: 'Table of Contents',
      level: 1,
      required: true,
      contentType: 'list',
      placeholder: 'Auto-generated table of contents',
    },
    {
      id: 'introduction',
      title: '1. Introduction',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'introduction-purpose',
          title: '1.1 Purpose',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Purpose of the validation study',
        },
        {
          id: 'introduction-scope',
          title: '1.2 Scope',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Scope and boundaries of the validation',
        },
        {
          id: 'introduction-references',
          title: '1.3 Referenced Documents',
          level: 2,
          required: true,
          contentType: 'list',
          placeholder: 'List of referenced protocols, standards, and guidelines',
        },
      ],
    },
    {
      id: 'study-design',
      title: '2. Study Design',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'study-design-summary',
          title: '2.1 Study Summary',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Overview of study design and objectives',
        },
        {
          id: 'study-design-endpoints',
          title: '2.2 Endpoints',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Table of primary and secondary endpoints',
        },
        {
          id: 'study-design-sample-size',
          title: '2.3 Sample Size Justification',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Statistical justification for sample size',
        },
        {
          id: 'study-design-statistical-methods',
          title: '2.4 Statistical Methods',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Description of statistical analysis methods',
        },
      ],
    },
    {
      id: 'protocol-history',
      title: '3. Protocol History',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'protocol-history-current',
          title: '3.1 Current Protocol Version',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Current protocol version and approval date',
        },
        {
          id: 'protocol-history-amendments',
          title: '3.2 Amendment History',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Table of all protocol amendments with dates and reasons',
        },
      ],
    },
    {
      id: 'study-results',
      title: '4. Study Results',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'results-data-overview',
          title: '4.1 Data Overview',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Import version, row count, data summary',
        },
        {
          id: 'results-per-endpoint',
          title: '4.2 Results per Endpoint',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder: 'Dynamic table: Endpoint, N, Result, 95% CI, Target, Status',
        },
        {
          id: 'results-statistical-analysis',
          title: '4.3 Statistical Analysis',
          level: 2,
          required: true,
          contentType: 'mixed',
          placeholder: 'Statistical significance testing and confidence intervals',
        },
      ],
    },
    {
      id: 'soa-comparison',
      title: '5. State of the Art Comparison',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'soa-benchmark-sources',
          title: '5.1 Benchmark Sources',
          level: 2,
          required: true,
          contentType: 'list',
          placeholder: 'References to SOA benchmark sources',
        },
        {
          id: 'soa-comparison-table',
          title: '5.2 Comparison Table',
          level: 2,
          required: true,
          contentType: 'table',
          placeholder:
            'Dynamic table: Endpoint, Result, SOA Benchmark, Status (MET/NOT_MET), Source',
        },
        {
          id: 'soa-analysis',
          title: '5.3 Analysis',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Interpretation of SOA comparison results',
        },
      ],
    },
    {
      id: 'discussion-conclusions',
      title: '6. Discussion & Conclusions',
      level: 1,
      required: true,
      contentType: 'mixed',
      subsections: [
        {
          id: 'discussion-summary',
          title: '6.1 Results Summary',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Summary of key findings',
        },
        {
          id: 'discussion-limitations',
          title: '6.2 Limitations',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Study limitations and constraints',
        },
        {
          id: 'discussion-conclusions',
          title: '6.3 Conclusions',
          level: 2,
          required: true,
          contentType: 'text',
          placeholder: 'Final conclusions and regulatory compliance statement',
        },
      ],
    },
    {
      id: 'appendix-amendments',
      title: 'Appendix A: Amendment History Details',
      level: 1,
      required: false,
      contentType: 'table',
      placeholder: 'Detailed amendment history with change descriptions',
    },
    {
      id: 'appendix-data',
      title: 'Appendix B: Data Import Summary',
      level: 1,
      required: false,
      contentType: 'mixed',
      placeholder: 'Raw data summary and import metadata',
    },
  ],
};
